module.exports = router => router()
  .namespace('/api/v1', api => api()
    .get('/me', { to: 'API.data' })
    .get('/orgs', { to: 'API.orgs' })
    .get('/boards/:org_id', { to: 'API.list' })
    .put('/boards/:org_id', { to: 'API.board' })
    .delete('/boards/:board_id', { to: 'API.remove' })
    .get('/cards/:board_id', { to: 'API.group' })
    .get('/login', { to: 'API.auth' })
    .post('/session', { to: 'API.token' })
    .delete('/session', { to: 'API.clear' }));
